support for report generate command
LambdaTest/lambdatest-cypress-cli pull request #47
Opened 2021-07-15 05:35 UTC by asad9711

https://lambdatest.atlassian.net/browse/MLE-5021

2021-08-02 02:32 UTC, takshch requested changes

2021-08-02 02:32 UTC, takshch commented on commands/report_generate.js
> +        if ("user" in args) {
Please use `hasOwnProperty()` because `hasOwnProperty()` searches only within the own properties of the object.

2021-08-02 02:32 UTC, takshch commented on commands/report_generate.js
> +        if ("access_key" in args) {
Same!

2021-08-02 02:32 UTC, takshch commented on commands/report_generate.js
> +        if (!("buildId" in args)) {
Same!

2021-08-02 02:32 UTC, takshch commented on commands/report_generate.js
> +        }
NIT: Please remove few empty lines which is of no use or lint it.

2021-08-02 02:32 UTC, takshch commented on commands/report_generate.js
> +                "build_id": Number(args.buildId)
Somewhere double quote(") is used and somewhere single quote(') is used.
Can you please tell me whether LambdaTest using it's own style guide for JS or not!

2021-08-02 02:32 UTC, takshch commented on commands/report_generate.js
> +            if (res.statusCode == "401") {
Either all `res.statusCode`  condition should be check in string format or in number.
Mixed used of string and number conditional checking can cause unpredictable bug or issue.

```js 
if (res.statusCode === 401) 
```

2021-08-02 02:32 UTC, takshch commented on commands/report_generate.js
> +            } else if(res.statusCode == 400){
Please use `===` strict equality comparision.

2021-08-02 02:32 UTC, takshch commented on commands/report_generate.js
> +            }  else if (res.statusCode == 200) {
same!

2021-08-02 02:32 UTC, takshch commented on commands/utils/constants.js
>  }
NIT: Please add empty line at the end.

2021-08-02 02:32 UTC, takshch commented on commands/report_generate.js
> +
NIT: Please remove one empty line from 4-5 line. One empty line is sufficient to generate difference.

2021-08-17 14:26 UTC, asad9711 commented
not required

2021-08-17 14:26 UTC, closed without merging